name: use
description: ->
  Use - A cost-effective open source user identity management platform
version: 0.0.0
repository: https://github.com/odroe/use

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.3
  spry: ^2.3.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
